# Generated by Django 4.2.16 on 2024-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='delete',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='read',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='permission',
            name='write',
            field=models.TextField(null=True),
        ),
    ]
